<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>1 Ошибка в setTimeout</title>
    </head>
    <body>
        <!-- Начало задания "1 Ошибка в setTimeout" -->
        <script>
            'use strict';
            // Что вы думаете? Выполнится ли .catch? Поясните свой ответ.
            new Promise(function (resolve, reject) {
                setTimeout(() => {
                    throw new Error('Whoops!');
                }, 1000);
            }).catch(alert);

            // ОТВЕТ: не выполнится, так как обрабатываются только синхронные ошибки
        </script>
        <!-- Конец задания "1 Ошибка в setTimeout" -->
    </body>
</html>
